"""Single feed registry: curated feeds.json + the imported world catalog.

feeds.json is the hand-verified list (with realtime URLs, timezones, notes).
feeds_world.json is generated by scripts/import_catalog.py from the official
MobilityData catalog — ~1500 keyless GTFS feeds worldwide. A curated entry
always wins over a world entry with the same id.
"""

from __future__ import annotations

import json
import os

_ROOT = os.path.join(os.path.dirname(__file__), "..")


def load() -> dict[str, dict]:
    feeds: dict[str, dict] = {}
    world_path = os.path.join(_ROOT, "feeds_world.json")
    if os.path.exists(world_path):
        for f in json.load(open(world_path))["feeds"]:
            feeds[f["id"]] = f
    for f in json.load(open(os.path.join(_ROOT, "feeds.json")))["feeds"]:
        feeds[f["id"]] = f  # curated overrides world
    return feeds
