"""Single feed registry: curated feeds.json + the imported world catalog.

feeds.json is the hand-verified list (with realtime URLs, timezones, notes).
feeds_world.json is generated by scripts/import_catalog.py from the official
MobilityData catalog — ~1500 keyless GTFS feeds worldwide. A curated entry
always wins over a world entry with the same id.
"""

from __future__ import annotations

import json
import os

from .paths import registry_file


def load() -> dict[str, dict]:
    feeds: dict[str, dict] = {}
    world_path = registry_file("feeds_world.json")
    if os.path.exists(world_path):
        with open(world_path, encoding="utf-8") as fh:
            world = json.load(fh)
        for f in world["feeds"]:
            feeds[f["id"]] = f
    with open(registry_file("feeds.json"), encoding="utf-8") as fh:
        curated = json.load(fh)
    for f in curated["feeds"]:
        feeds[f["id"]] = f  # curated overrides world
    return feeds
